baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Fat and Badass'
primary: true
siteGroup: 3f5d047a-947c-4463-9e7b-1838c558110d # Fat and Badass
sortOrder: 1
