dateModified: 1744514059
email:
  fromEmail: vince@vincewebdesigns.com
  fromName: 'Fat and Badass'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3f5d047a-947c-4463-9e7b-1838c558110d: 'Fat and Badass' # Fat and Badass
    850b93f5-9a4f-454e-989b-d479daa0452e: 'Fat and Badass' # Fat and Badass
system:
  edition: solo
  live: true
  name: 'Fat and Badass'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
